name: Unit Tests

on:
  pull_request:
    branches: [main]
  workflow_call:

permissions:
  contents: read

env:
  PLATFORMS: linux/arm64,linux/amd64,darwin/arm64
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      # - name: Add deploy key
      #   uses: webfactory/ssh-agent@v0.10.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          problem-matchers: true

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v4
      #   with:
      #     platforms: ${{ env.PLATFORMS }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v4
      #   with:
      #     platforms: ${{ env.PLATFORMS }}

      - name: Run Mage
        uses: magefile/mage-action@v4
        with:
          version: latest
